platform :ios, '5.1'
pod 'SSKeychain', '~> 1.1.0'
pod 'MNMPullToRefresh', '~> 0.0.1'
pod 'UI7Kit', '~> 0.9.17'
pod 'MCSwipeTableViewCell', '~> 2.1.0'

# a submodule-less setup for development in both at the same time
# pod 'PryvApiKit', :path => '../../sdk-objectivec-apple/PryvApiKit.podspec'

# after PryvApiKit would appear in Pods repository
# pod 'PryvApiKit', :head

 pod 'PryvApiKit', :git => 'https://github.com/pryv/sdk-objectivec-apple.git', :commit => '41eeb475807050da9cc06d2abe41205d53c0b42c'
